
# this is the name of the main maude module
LANGUAGE_NAME = JAVA

# this are all interesting modules (used to latexify)
LANGUAGE_MODULES = JAVA

LATEX_STYLE = bb
LATEX_TOPMATTER = README.tex

#this is the basename of the main file
MAIN_FILE = java

# this is a space-separated list of basename maude files to run
TESTS = java-test.m

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
