#!/bin/bash
printf "bst-find\n"
krun -cMainClass="ListItem(\"bst\")"      --prove verification/bst-find-spec.k       bst.java.pkast      --smt_prelude ../../k/k-distribution/include/z3/search_tree.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false" 
printf "bst-insert\n"
 krun -cMainClass="ListItem(\"bst\")"      --prove verification/bst-insert-spec.k     bst.java.pkast      --smt_prelude ../../k/k-distribution/include/z3/search_tree.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false" 
printf "bst-delete(assertionError)\n"
 krun -cMainClass="ListItem(\"bst\")"      --prove verification/bst-delete-spec.k     bst.java.pkast      --smt_prelude ../../k/k-distribution/include/z3/search_tree.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false" 
printf "avl-find\n"
 krun -cMainClass="ListItem(\"avl\")"      --prove verification/avl-find-spec.k       avl.java.pkast      --smt_prelude ../../k/k-distribution/include/z3/search_tree.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false" 
printf "avl-insert(this one takes more than a thousand steps to prove, may need ulimit -c unlimited before starting Java)\n"
 krun -cMainClass="ListItem(\"avl\")"      --prove verification/avl-insert-spec.k     avl.java.pkast      --smt_prelude ../../k/k-distribution/include/z3/search_tree.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false" 
printf "avl-delete(assertionError)\n"
 krun -cMainClass="ListItem(\"avl\")"      --prove verification/avl-delete-spec.k     avl.java.pkast      --smt_prelude ../../k/k-distribution/include/z3/search_tree.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false" 
printf "rbt-find\n"
 krun -cMainClass="ListItem(\"rbt\")"      --prove verification/rbt-find-spec.k       rbt.java.pkast      --smt_prelude ../../k/k-distribution/include/z3/search_tree.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false"
printf "rbt-insert\n"
 krun -cMainClass="ListItem(\"rbt\")"      --prove verification/rbt-insert-spec.k       rbt.java.pkast      --smt_prelude ../../k/k-distribution/include/z3/search_tree.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false"
printf "rbt-delete\n"
 krun -cMainClass="ListItem(\"rbt\")"      --prove verification/rbt-delete-spec.k       rbt.java.pkast      --smt_prelude ../../k/k-distribution/include/z3/search_tree.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false"
printf "reverse\n"
 krun -cMainClass="ListItem(\"listNode\")" --prove verification/reverse-spec.k        listNode.java.pkast --smt_prelude ../../k/k-distribution/include/z3/sorted_list.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false" 
printf "append\n"
 krun -cMainClass="ListItem(\"listNode\")" --prove verification/append-spec.k         listNode.java.pkast --smt_prelude ../../k/k-distribution/include/z3/sorted_list.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false" 
printf "bubble-sort\n"
 krun -cMainClass="ListItem(\"listNode\")" --prove verification/bubble-sort-spec.k    listNode.java.pkast --smt_prelude ../../k/k-distribution/include/z3/sorted_list.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false" 
printf "insertion-sort\n"
 krun -cMainClass="ListItem(\"listNode\")" --prove verification/insertion-sort-spec.k listNode.java.pkast --smt_prelude ../../k/k-distribution/include/z3/sorted_list.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false" 
printf "quick-sort\n"
 krun -cMainClass="ListItem(\"listNode\")" --prove verification/quicksort-spec.k      listNode.java.pkast --smt_prelude ../../k/k-distribution/include/z3/sorted_list.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false" 
printf "merge-sort\n"
 krun -cMainClass="ListItem(\"listNode\")" --prove verification/merge-sort-spec.k     listNode.java.pkast --smt_prelude ../../k/k-distribution/include/z3/sorted_list.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false" 
printf "sum\n"
krun -cMainClass="ListItem(\"sum\")"      --prove verification/sum-iterative-spec.k     sum.java.pkast      --smt_prelude ../../k/k-distribution/include/z3/basic.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false" 
printf "min\n"
krun -cMainClass="ListItem(\"min\")"      --prove verification/min-spec.k               min.java.pkast      --smt_prelude ../../k/k-distribution/include/z3/basic.smt2 -v --debug -d verification --symbolic-execution --statistics on --parser "cat" -cDissolveAllExceptOut="false" 
